### ISSUE TITLE
yarn add  @tailwindcss/typography fails

### ISSUE THREAD

**Issue by tenerecodes** [tailwindlabs/tailwindcss-typography#132]
Hello there, i wanted to try this package but i get 404 not found error.

node version : "14.15.4"
command: "yarn add @tailwindcss/typography"
response:
yarn add v1.22.5
[1/4] Resolving packages...
[2/4] Fetching packages...
error An unexpected error occurred: "https://registry.yarnpkg.com/cross-spagl/-/cross-spagl-7.0.3.tgz: Request failed \"404 Not Found\"".
info If you think this is a bug, please open a bug report with the information provided in "/usr/src/app/yarn-error.log".
info Visit https://yarnpkg.com/en/docs/cli/add for documentation about this command.

yarn-error.log:
Arguments: 
  /usr/local/bin/node /opt/yarn-v1.22.5/bin/yarn.js add @tailwindcss/typography

PATH: 
  /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin

Yarn version: 
  1.22.5

Node version: 
  14.15.4

Platform: 
  linux x64

Trace: 
  Error: https://registry.yarnpkg.com/cross-spagl/-/cross-spagl-7.0.3.tgz: Request failed "404 Not Found"
      at ResponseError.ExtendableBuiltin (/opt/yarn-v1.22.5/lib/cli.js:696:66)
      at new ResponseError (/opt/yarn-v1.22.5/lib/cli.js:802:124)
      at Request.<anonymous> (/opt/yarn-v1.22.5/lib/cli.js:67058:16)
      at Request.emit (events.js:315:20)
      at Request.module.exports.Request.onRequestResponse (/opt/yarn-v1.22.5/lib/cli.js:141626:10)
      at ClientRequest.emit (events.js:315:20)
      at HTTPParser.parserOnIncomingClient (_http_client.js:641:27)
      at HTTPParser.parserOnHeadersComplete (_http_common.js:126:17)
      at TLSSocket.socketOnData (_http_client.js:509:22)
      at TLSSocket.emit (events.js:315:20)

npm manifest: 
  {
    "name": "agl",
    "version": "1.0.0",
    "private": true,
    "scripts": {
      "dev": "nuxt",
      "build": "nuxt build",
      "start": "nuxt start",
      "generate": "nuxt generate",
      "lint:js": "eslint --ext .js,.vue --ignore-path .gitignore .",
      "lint": "yarn lint:js"
    },
    "dependencies": {
      "core-js": "^3.6.5",
      "nuxt": "^2.14.6"
    },
    "devDependencies": {
      "@nuxtjs/eslint-config": "^3.1.0",
      "@nuxtjs/eslint-module": "^2.0.0",
      "@nuxtjs/tailwindcss": "^3.1.0",
      "babel-eslint": "^10.1.0",
      "eslint": "^7.10.0",
      "eslint-config-prettier": "^6.12.0",
      "eslint-plugin-nuxt": "^1.0.0",
      "eslint-plugin-prettier": "^3.1.4",
      "prettier": "^2.1.2"
    }
  }

yarn manifest: 
  No manifest

Lockfile: 
  # THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
  # yarn lockfile v1

**Comment by tenerecodes** [comment]
Seems irrelevant because i get this error with every `yarn add` now
