### ISSUE TITLE
Issue with installing and typography

### ISSUE THREAD

**Issue by ironyh** [tailwindlabs/tailwindcss-typography#249]
### What version of @tailwindcss/typography are you using?

@tailwindcss/typography@next

### What version of Node.js are you using?

v16.13.2

### What browser are you using?

Chrome

### What operating system are you using?

Windows

### Reproduction repository

https://github.com/ironyh/tailwind_issue

### Describe your issue

Created projcect with ```vue create```.
Added tailwind with ```add tailwind```
Added typography with ```npm install -D @tailwindcss/typography@next --legacy-peer-deps``` and added it in tailwind.config.js

Getting following error:
```
Failed to compile.

./src/assets/tailwind.css (./node_modules/css-loader/dist/cjs.js??ref--7-oneOf-3-1!./node_modules/postcss-loader/src??ref--7-oneOf-3-2!./src/assets/tailwind.css)
Module build failed (from ./node_modules/postcss-loader/src/index.js):
TypeError: Cannot read properties of undefined (reading '700')
    at Object.<anonymous> (C:\Users\Arash\Code\offline_editor\node_modules\@tailwindcss\typography\src\styles.js:949:38)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (C:\Users\Arash\Code\offline_editor\node_modules\@tailwindcss\typography\src\index.js:4:16)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (C:\Users\Arash\Code\offline_editor\tailwind.config.js:10:5)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
```
Output looks good:
```
Found Tailwind CSS config file: c:\Users\Arash\Code\offline_editor\tailwind.config.js
Loaded postcss v7.0.39: c:\Users\Arash\Code\offline_editor\node_modules\postcss
Loaded tailwindcss v2.2.17: c:\Users\Arash\Code\offline_editor\node_modules\tailwindcss
Found Tailwind CSS config file: c:\Users\Arash\Code\offline_editor\tailwind.config.js
Loaded postcss v7.0.39: c:\Users\Arash\Code\offline_editor\node_modules\postcss
Loaded tailwindcss v2.2.17: c:\Users\Arash\Code\offline_editor\node_modules\tailwindcss
```
So I don't know what it is that goes wrong

**Comment by adamwathan** [comment]
Hey! You need to install the latest version of Tailwind, it looks like whatever that `add tailwind` shortcut in Vue CLI is is adding v2. The latest typography plugin version is only compatible with Tailwind v3+.

I don’t think Vue CLI is actively developed anymore (apologies if I’m wrong) and instead it’s recommended to use Vite. We have a guide on installing Tailwind 3 with Vite here:

https://tailwindcss.com/docs/guides/vite#header
